config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :bookmarks
  resources :movies
  resources :lists
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :list, uniqueness: { scope: :movie }
end

app/models/list.rb
class List < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
  has_many :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: %i[show edit update destroy]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    if @bookmark.save
      # No need for app/views/bookmarks/create.html.erb
      redirect_to bookmark_path(@bookmark)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark.destroy
    # No need for app/views/bookmarks/destroy.html.erb
    redirect_to bookmarks_path, status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :references.movie, :references.list)
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[show edit update destroy]

  def index
    @lists = List.all
  end

  def show
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      # No need for app/views/lists/create.html.erb
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list.destroy
    # No need for app/views/lists/destroy.html.erb
    redirect_to lists_path, status: :see_other
  end

  private

  def list_params
    params.require(:list).permit(:comment, :references.movie, :references.list)
  end

  def set_list
    @list = List.find(params[:id])
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1>My Lists</h1>
<ul>
  <% @lists.each do |list| %>
    <li><%= link_to restaurant.name, list_path(list)%></li>
  <% end %>
  <%= link_to "+ Add a new list", new_list_path%>
</ul>

app/views/lists/show.html.erb
<h2><%= @list.name %></h2>

<p><strong>Reviews</strong></p>
<ul class="list-group">
  <% @list.name.each do |review| %>
    <li class="list-group-item"><%= review.content %></li>
  <% end %>
</ul>
<br>

<%= simple_form_for [@list] do |f| %>
  <%= f.input :rating %>
  <%= f.input :content %>
  <%= f.submit %>
<% end %>

<ul>
  <li><%= link_to "Back to list", lists_path%></li>
  <li><%= link_to "Edit", edit_list_path%></li>
  <li><%= link_to "Delete",
    list_path(@list),
    data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
  %></li>
</ul>